language: php
php:
    - 5.3.3
    - 5.5

before_script:
    - composer install --no-interaction --dev --prefer-source

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
